services:
  db:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db  # fixed: underscore to match the volumes section
      - ./db:/docker-entrypoint-initdb.d/
  
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - db
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /var/www/html
    

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:5173"
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
          ignore:
            - node_modules

volumes:
  mongo_data:  # declared here, used above